import { NextRequest, NextResponse } from "next/server";
import { getEnabledPosterJobs, getPosterByDate, createPoster, updatePoster, logActivity, getBrandKit } from "@/lib/firebase/firestore";
import { uploadPosterImage } from "@/lib/firebase/storage";
import { findOnePhotoId, downloadPhotoBuffer } from "@/lib/freepik";

const CRON_SECRET = process.env.CRON_SECRET;

function getTodayISO() {
  return new Date().toISOString().slice(0, 10);
}

export async function GET(request: NextRequest) {
  const auth = request.headers.get("Authorization");
  if (CRON_SECRET && auth !== `Bearer ${CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let processed = 0;
  let skipped = 0;
  let failed = 0;

  try {
    const jobs = await getEnabledPosterJobs();
    const today = getTodayISO();

    for (const job of jobs) {
      const existing = await getPosterByDate(
        job.userId,
        job.brandKitId,
        today,
        1
      );
      if (existing) {
        skipped++;
        continue;
      }

      try {
        const posterData = {
          userId: job.userId,
          brandKitId: job.brandKitId,
          createdForDate: today,
          headline: "",
          subheadline: "",
          body: "",
          cta: "",
          hashtags: [] as string[],
          imageUrl: "",
          status: "generated" as const,
          error: null as string | null,
          version: 1,
        };
        const poster = await createPoster(job.userId, posterData);
        const placeholderPng = Buffer.from(
          "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==",
          "base64"
        );
        let imageBuffer: Buffer = placeholderPng;
        let imageContentType = "image/png";
        if (process.env.FREEPIK_API_KEY) {
          try {
            const brandKit = await getBrandKit(job.userId, job.brandKitId);
            const searchTerm =
              brandKit?.styleNotes?.trim() ||
              brandKit?.sampleContent?.trim() ||
              "minimal social media background";
            const photoId = await findOnePhotoId(searchTerm);
            if (photoId) {
              const downloaded = await downloadPhotoBuffer(photoId, "large");
              imageBuffer = downloaded.buffer;
              imageContentType = downloaded.contentType;
            }
          } catch {
            // keep placeholder
          }
        }
        const imageUrl = await uploadPosterImage(
          job.userId,
          poster.id,
          imageBuffer,
          imageContentType
        );
        await updatePoster(job.userId, poster.id, {
          headline: "Daily poster",
          subheadline: today,
          body: "Generated by cron.",
          cta: "Learn more",
          hashtags: [],
          imageUrl,
        });
        await logActivity(job.userId, poster.id, "generated");
        processed++;
      } catch {
        failed++;
      }
    }

    return NextResponse.json({ processed, skipped, failed });
  } catch (e) {
    return NextResponse.json(
      { error: "Cron failed", processed, skipped, failed },
      { status: 500 }
    );
  }
}
