import Link from "next/link";

export const metadata = {
  title: "Terms of Service | ArtMaster",
  description: "Terms and conditions for using the ArtMaster platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg-base text-text-primary">
      <header className="border-b border-border-subtle">
        <div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link href="/" className="font-semibold text-text-primary">
            ArtMaster
          </Link>
          <Link
            href="/"
            className="font-mono text-xs text-text-muted hover:text-text-primary"
          >
            ← Back
          </Link>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-2xl font-semibold tracking-tight mb-2">
          Terms of Service
        </h1>
        <p className="font-mono text-xs text-text-muted mb-8">
          Last updated: 28 February 2026
        </p>

        <section className="space-y-8 text-sm text-text-secondary leading-relaxed">

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">1. Acceptance of Terms</h2>
            <p>
              By creating an account or using ArtMaster (&quot;the Platform&quot;, &quot;we&quot;, &quot;us&quot;), you agree to
              these Terms of Service. If you do not agree, do not use the Platform. These terms apply
              to all users, including free and paid plan subscribers.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">2. Description of Service</h2>
            <p>
              ArtMaster is an AI-powered platform that generates branded social media posters for
              businesses. The Platform uses artificial intelligence to create copy and images based on
              your brand kit. Generated content is intended for your own marketing use.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">3. Account Responsibilities</h2>
            <ul className="list-disc list-inside space-y-1 text-text-muted mt-2">
              <li>You must provide accurate information when creating your account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must be at least 18 years old to use the Platform.</li>
              <li>One account per person or business. You may not share accounts.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">4. Plans, Payments & Billing</h2>
            <p>
              ArtMaster offers Free, Pro, and Business subscription plans. Paid plans are billed
              monthly. By subscribing to a paid plan, you authorise us to charge your selected payment
              method on a recurring basis.
            </p>
            <ul className="list-disc list-inside space-y-1 text-text-muted mt-2">
              <li>Prices are displayed in your local currency where available, and charged in USD or TZS depending on your country.</li>
              <li>Poster generation limits reset on your monthly billing date.</li>
              <li>Unused poster credits do not roll over to the next month.</li>
              <li>You may upgrade or downgrade your plan at any time. Downgrades take effect at the next billing cycle.</li>
              <li>We do not offer refunds for partial months or unused credits.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">5. AI-Generated Content</h2>
            <p>
              Content generated by ArtMaster (including copy, images, and posters) is produced by
              artificial intelligence. You acknowledge that:
            </p>
            <ul className="list-disc list-inside space-y-1 text-text-muted mt-2">
              <li>AI-generated content may not always be accurate, appropriate, or suitable for your specific use case.</li>
              <li>You are solely responsible for reviewing content before publishing or distributing it.</li>
              <li>You own the output generated using your brand kit and account, subject to the licences of our underlying AI providers (OpenAI, Freepik).</li>
              <li>ArtMaster does not guarantee that generated content is free from third-party intellectual property claims.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">6. Acceptable Use</h2>
            <p>You agree not to use ArtMaster to:</p>
            <ul className="list-disc list-inside space-y-1 text-text-muted mt-2">
              <li>Generate content that is illegal, harmful, defamatory, or violates any third-party rights.</li>
              <li>Impersonate another person, brand, or organisation.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Platform or its APIs.</li>
              <li>Circumvent plan limits or access controls.</li>
              <li>Use the Platform for spam, phishing, or any deceptive marketing practices.</li>
            </ul>
            <p className="mt-2">
              We reserve the right to suspend or terminate accounts that violate these rules without
              prior notice.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">7. Intellectual Property</h2>
            <p>
              The ArtMaster platform, its design, code, and branding are owned by ArtMaster and
              protected by applicable intellectual property laws. You may not copy, reproduce, or
              redistribute any part of the Platform without written permission.
            </p>
            <p className="mt-2">
              You retain ownership of the brand assets (logos, names, colours) you upload to the
              Platform. By uploading them, you grant ArtMaster a limited licence to use them solely
              for the purpose of generating your posters.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">8. Third-Party Services</h2>
            <p>
              ArtMaster integrates with third-party services including OpenAI, Freepik, Firebase,
              Cloudinary, and Snippe Payments. Your use of these services through our Platform is
              also subject to their respective terms and privacy policies. We are not responsible for
              the actions or availability of third-party services.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">9. Social Media Integrations</h2>
            <p>
              When you connect a social media account (such as Instagram or Facebook) to ArtMaster,
              you authorise us to publish content to that account on your behalf. You can revoke this
              access at any time from your dashboard or directly from the social platform&apos;s settings.
              We are not responsible for content published in error — always review your scheduled
              posts.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">10. Disclaimers & Limitation of Liability</h2>
            <p>
              ArtMaster is provided &quot;as is&quot; without warranties of any kind. We do not guarantee
              uninterrupted service, error-free generation, or specific business results from using
              the Platform.
            </p>
            <p className="mt-2">
              To the maximum extent permitted by law, ArtMaster shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Platform, including
              loss of revenue, data, or business opportunities.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">11. Termination</h2>
            <p>
              You may delete your account at any time from your dashboard settings. We may suspend or
              terminate your account if you violate these Terms. Upon termination, your data may be
              deleted after a reasonable retention period in accordance with our Privacy Policy.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">12. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of significant changes
              via email or an in-app notice. Continued use of the Platform after changes take effect
              constitutes your acceptance of the updated Terms.
            </p>
          </div>

          <div>
            <h2 className="text-base font-medium text-text-primary mb-2">13. Governing Law</h2>
            <p>
              These Terms are governed by the laws of Tanzania. Any disputes shall be resolved in the
              courts of Tanzania, unless otherwise required by applicable consumer protection laws in
              your country.
            </p>
          </div>

        </section>

        <p className="mt-10 font-mono text-xs text-text-muted">
          Questions about these terms? Contact us through the app or at your support email.
        </p>

        <div className="mt-6 flex gap-4 font-mono text-xs">
          <Link href="/privacy" className="text-accent hover:underline">
            Privacy Policy
          </Link>
        </div>
      </main>
    </div>
  );
}
