/**
 * Editable poster layout spec.
 *
 * The background image is a text-free Cloudinary URL generated by Seedream/Gemini.
 * Every text, logo, and shape element lives here as JSON and is rendered by
 * the Fabric.js editor on the frontend — never baked into the background image.
 *
 * Coordinates: x, y, width, height are percentages (0–100) of poster dimensions.
 * The Fabric canvas scales them to actual px when mounting.
 */

export interface PosterLayout {
  posterId?: string;
  backgroundImageUrl: string;
  /** Dominant / fallback colour while background loads (e.g. brand primary). */
  backgroundDominantColor: string;
  width: number;   // e.g. 1080
  height: number;  // e.g. 1080
  elements: PosterElement[];
}

export type PosterElement =
  | TextElement
  | LogoElement
  | ShapeElement
  | PriceTagElement;

/** Shared base fields for every element. */
interface BaseElement {
  id: string;
  x: number;       // % from left (0–100)
  y: number;       // % from top  (0–100)
  width: number;   // % of poster width
  opacity: number; // 0–1
  locked: boolean;
  zIndex: number;
}

export interface TextElement extends BaseElement {
  type: "text";
  content: string;
  fontSize: number;       // px at 1080 base
  fontFamily: string;     // e.g. "Syne", "DM Sans", "Playfair Display"
  fontWeight: number;     // 400 | 600 | 700 | 900
  color: string;          // "#FFFFFF"
  textAlign: "left" | "center" | "right";
  lineHeight: number;     // e.g. 1.2
  letterSpacing: number;  // em units, e.g. 0.05
  /** Optional pill / badge background behind the text. */
  backgroundColor?: string;
  backgroundPadding?: number; // px
  borderRadius?: number;       // px
}

export interface LogoElement extends BaseElement {
  type: "logo";
  src: string;    // Cloudinary URL
  height: number; // % of poster height (auto or explicit)
}

export interface ShapeElement extends BaseElement {
  type: "shape";
  shape: "rectangle" | "circle" | "pill";
  height: number;          // % of poster height
  fill: string;            // "#000000"
  borderRadius?: number;   // px
}

export interface PriceTagElement extends BaseElement {
  type: "price";
  price: string;    // "Tsh 45,000"
  currency: string; // "TZS"
  fontSize: number;
  color: string;
}

// ---------------------------------------------------------------------------
// Brief passed to generateLayout (assembled from copy + recommendation)
// ---------------------------------------------------------------------------

export interface LayoutBrief {
  headline: string;
  subheadline: string;
  cta: string;
  hashtags: string[];
  body?: string;
  visualMood?: string;
  designStyle?: string;
}

// ---------------------------------------------------------------------------
// Raw output from the GPT layout call (before we inject the logo element etc.)
// ---------------------------------------------------------------------------

export interface LayoutGptOutput {
  backgroundPrompt: string;
  backgroundStyle?: "dark" | "light" | "vibrant" | "minimal";
  elements: PosterElement[];
}
